# Generated by Django 4.0.3 on 2022-06-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(null=True, verbose_name='コメント')),
                ('enable', models.IntegerField(null=True, verbose_name='有効')),
            ],
        ),
        migrations.CreateModel(
            name='DevOpsSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('maturity', models.IntegerField(null=True, verbose_name='成熟度')),
            ],
        ),
        migrations.CreateModel(
            name='IconMater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('icon', models.ImageField(blank=True, max_length=1024, upload_to='icons', verbose_name='icon')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('maturity', models.IntegerField(null=True, verbose_name='成熟度')),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('maturity', models.IntegerField(null=True, verbose_name='成熟度')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('subtitle', models.CharField(max_length=100, verbose_name='サブタイトル')),
                ('first_name', models.CharField(max_length=100, verbose_name='名')),
                ('last_name', models.CharField(max_length=100, verbose_name='氏')),
                ('job', models.CharField(max_length=100, null=True, verbose_name='職業')),
                ('introduction', models.CharField(max_length=300, null=True, verbose_name='自己紹介')),
                ('face_photo', models.ImageField(blank=True, max_length=1024, null=True, upload_to='profile', verbose_name='顔写真')),
                ('sub_photo', models.ImageField(blank=True, max_length=1024, null=True, upload_to='profile', verbose_name='サブ写真')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, max_length=1024, upload_to='works', verbose_name='メインビジュアル')),
                ('private', models.IntegerField(default=0, verbose_name='プライベート作品')),
                ('description', models.CharField(max_length=300, verbose_name='概要')),
                ('url', models.CharField(max_length=1024, null=True, verbose_name='URL')),
                ('repository_url', models.CharField(max_length=1024, null=True, verbose_name='リポジトリURL')),
                ('sort', models.IntegerField(verbose_name='順序')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLibrarySkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='順序')),
                ('library_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_skills', to='portfolio.libraryskill')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lib_works', to='portfolio.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkLanguageSkillRelationShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='順序')),
                ('language_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_skills', to='portfolio.languageskill')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lang_works', to='portfolio.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDevOpsSkillRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0, verbose_name='順序')),
                ('dev_ops_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_ops_skills', to='portfolio.devopsskill')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_works', to='portfolio.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titile', models.CharField(max_length=100, verbose_name='サブタイトル')),
                ('start_date', models.DateTimeField(verbose_name='制作開始')),
                ('end_date', models.DateTimeField(null=True, verbose_name='制作終了')),
                ('processes', models.CharField(max_length=300, null=True, verbose_name='担当工程')),
                ('detail_description', models.TextField(null=True, verbose_name='詳細')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_details', to='portfolio.work')),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetworkService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('url', models.CharField(max_length=1024, verbose_name='URL')),
                ('icon_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icon_masters', to='portfolio.iconmater')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='portfolio.profile')),
            ],
        ),
    ]
