version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: nginx
    volumes:
      - ./web/gunicorn.conf:/etc/nginx/conf.d/default.conf
      - gunicorn:/var/run/gunicorn
      - static:/var/www/static
      - media:/var/www/media
    ports:
      - "8888:80"
    depends_on:
      - app

  app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - .:/workspace:cached
      - gunicorn:/var/run/gunicorn
      - static:/var/www/static
      - media:/var/www/media
    environment:
      TZ: "Asia/Tokyo"
    command: /bin/bash -c /workspace/app/bootstrap.sh
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - portfolio_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: portfolio_db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}

volumes:
    portfolio_data:
    gunicorn:
    static:
    media:
