# Generated by Django 4.0.3 on 2022-10-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetail',
            name='introduction',
            field=models.TextField(max_length=300, null=True, verbose_name='自己紹介'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(max_length=300, verbose_name='概要'),
        ),
    ]
