name: Deploy to VPS

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: kchihogi/portfolio

    - name: Extract metadata (tags, labels) for Docker
      id: meta-web
      uses: docker/metadata-action@v4
      with:
        images: kchihogi/portfolio-web

    - name: Build and push Docker image for app
      uses: docker/build-push-action@v3
      with:
        context: .
        file: app/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Docker image for web
      uses: docker/build-push-action@v3
      with:
        context: .
        file: web/Dockerfile
        push: true
        tags: ${{ steps.meta-web.outputs.tags }}
        labels: ${{ steps.meta-web.outputs.labels }}

    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2.3.1
    #   with:
    #     key: ${{ secrets.SSH_KEY }}
    #     name: id_rsa
    #     known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # - name: run deploy script
    #   run: bash deploy/deploy.sh
    #   env:
    #     USER: ${{ secrets.USER }}
    #     HOST: ${{ secrets.HOST }}
